name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        REPOSITORY=$(echo $GITHUB_REPOSITORY)  
        docker build . --file Dockerfile --tag ghcr.io/vinod-payyapilly/$REPOSITORY
        docker run ghcr.io/vinod-payyapilly/$REPOSITORY
        docker push ghcr.io/vinod-payyapilly/$REPOSITORY
      
